title: Wang Yizhe's Homepage
page-top-title: Wang Yizhe
top-section-bg-text: Electrical Engineering and Automation
home-subtitle: Wang Yizhe&ensp;|&ensp;王亦哲
copyright-text: '&copy; Wang Yizhe 2024.All Rights Reserved.'
